/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import Querys.Comandos;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;

/**
 *
 * @author Matheus
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {

        initComponents();
        Toolkit kit = Toolkit.getDefaultToolkit();
        Dimension monitor = kit.getScreenSize();

        int largura = monitor.width;
        int altura = monitor.height;

        largura *= 0.7;
        altura *= 0.7;
        setSize(largura, altura);
        setLocationRelativeTo(null);
        
        Comandos c1 = new Comandos();
        if (c1.getNv_acesso() == 1){
        jMenuAlteracaoLivro.setVisible(false);
        jMenuConsultarEmprestimo.setVisible(false);
        jMenuCadastro.setVisible(false);
        } else if(c1.getNv_acesso() == 2){
        jMenuCadastroFuncionarios.setVisible(false);
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuLivro = new javax.swing.JMenu();
        jMenuConsultaLivro = new javax.swing.JMenuItem();
        jMenuAlteracaoLivro = new javax.swing.JMenuItem();
        jMenuEmprestimo = new javax.swing.JMenu();
        jMenuRealizarEmprestimo = new javax.swing.JMenuItem();
        jMenuConsultarEmprestimo = new javax.swing.JMenuItem();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuCadastroClientes = new javax.swing.JMenuItem();
        jMenuCadastroFuncionarios = new javax.swing.JMenuItem();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuLogout = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout JDesktopLayout = new javax.swing.GroupLayout(JDesktop);
        JDesktop.setLayout(JDesktopLayout);
        JDesktopLayout.setHorizontalGroup(
            JDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );
        JDesktopLayout.setVerticalGroup(
            JDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 51, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBar1.setForeground(new java.awt.Color(0, 51, 204));

        jMenuLivro.setText("Livro");

        jMenuConsultaLivro.setText("Consulta de livros");
        jMenuConsultaLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultaLivroActionPerformed(evt);
            }
        });
        jMenuLivro.add(jMenuConsultaLivro);

        jMenuAlteracaoLivro.setText("Alteração de estoque de livros");
        jMenuAlteracaoLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlteracaoLivroActionPerformed(evt);
            }
        });
        jMenuLivro.add(jMenuAlteracaoLivro);

        jMenuBar1.add(jMenuLivro);

        jMenuEmprestimo.setBackground(new java.awt.Color(51, 153, 255));
        jMenuEmprestimo.setText("Emprestimo");

        jMenuRealizarEmprestimo.setText("Realizar emprestimo");
        jMenuRealizarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRealizarEmprestimoActionPerformed(evt);
            }
        });
        jMenuEmprestimo.add(jMenuRealizarEmprestimo);

        jMenuConsultarEmprestimo.setText("Consulta de emprestimo");
        jMenuConsultarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultarEmprestimoActionPerformed(evt);
            }
        });
        jMenuEmprestimo.add(jMenuConsultarEmprestimo);

        jMenuBar1.add(jMenuEmprestimo);

        jMenuCadastro.setText("Cadastro");

        jMenuCadastroClientes.setText("Cadastro de clientes");
        jMenuCadastroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroClientesActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadastroClientes);

        jMenuCadastroFuncionarios.setText("Cadastro de funcionários");
        jMenuCadastroFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroFuncionariosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadastroFuncionarios);

        jMenuBar1.add(jMenuCadastro);

        jMenuArquivo.setText("Arquivo");

        jMenuLogout.setText("Logout");
        jMenuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLogoutActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuLogout);

        jMenuSair.setText("Sair da aplicação");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuSair);

        jMenuBar1.add(jMenuArquivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDesktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDesktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLogoutActionPerformed
        //Comando para retornar a tela do login
        TelaLogin t1 = new TelaLogin();

        t1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuLogoutActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        // Comando para sair da aplicação
        System.exit(0);
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuConsultaLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultaLivroActionPerformed
        // TODO add your handling code here:
        FecharTela();
        TelaConsultaLivro t1 = new TelaConsultaLivro();
        JDesktop.add(t1);
        try {
            t1.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        t1.setClosable(true);
        t1.setVisible(true);
    }//GEN-LAST:event_jMenuConsultaLivroActionPerformed

    private void jMenuAlteracaoLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlteracaoLivroActionPerformed
        // TODO add your handling code here:
        FecharTela();
        TelaAlteraLivro t2 = new TelaAlteraLivro();
        JDesktop.add(t2);
        try {
            t2.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        t2.setClosable(true);
        t2.setVisible(true);
    }//GEN-LAST:event_jMenuAlteracaoLivroActionPerformed

    private void jMenuRealizarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRealizarEmprestimoActionPerformed
        // TODO add your handling code here:
         FecharTela();
        TelaRealizarEmprestimo t4 = new TelaRealizarEmprestimo();
        JDesktop.add(t4);
        try {
            t4.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        t4.setClosable(true);
        t4.setVisible(true);
       
    }//GEN-LAST:event_jMenuRealizarEmprestimoActionPerformed

    private void jMenuConsultarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultarEmprestimoActionPerformed
        // TODO add your handling code here:
         FecharTela();
        TelaConsultarEmprestimo t3 = new TelaConsultarEmprestimo();
        JDesktop.add(t3);
        try {
            t3.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        t3.setClosable(true);
        t3.setVisible(true);
    }//GEN-LAST:event_jMenuConsultarEmprestimoActionPerformed

    private void jMenuCadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroClientesActionPerformed
        // TODO add your handling code here:
         FecharTela();
        TelaCadastroClientes t5 = new TelaCadastroClientes();
        JDesktop.add(t5);
        try {
            t5.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        t5.setClosable(true);
        t5.setVisible(true);
    }//GEN-LAST:event_jMenuCadastroClientesActionPerformed

    private void jMenuCadastroFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroFuncionariosActionPerformed
        // TODO add your handling code here:
         FecharTela();
        TelaCadastroFuncionarios t6 = new TelaCadastroFuncionarios();
        JDesktop.add(t6);
        try {
            t6.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        t6.setClosable(true);
        t6.setVisible(true);
    }//GEN-LAST:event_jMenuCadastroFuncionariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JDesktop;
    private javax.swing.JMenuItem jMenuAlteracaoLivro;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuCadastroClientes;
    private javax.swing.JMenuItem jMenuCadastroFuncionarios;
    private javax.swing.JMenuItem jMenuConsultaLivro;
    private javax.swing.JMenuItem jMenuConsultarEmprestimo;
    private javax.swing.JMenu jMenuEmprestimo;
    private javax.swing.JMenu jMenuLivro;
    private javax.swing.JMenuItem jMenuLogout;
    private javax.swing.JMenuItem jMenuRealizarEmprestimo;
    private javax.swing.JMenuItem jMenuSair;
    // End of variables declaration//GEN-END:variables

    private void FecharTela() {

        JInternalFrame tela = JDesktop.getSelectedFrame();
        if (tela != null) {
            JDesktop.getSelectedFrame().dispose();
        }
    }
}
