/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;


import Querys.Comandos;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;




/**
 *
 * @author Matheus
 */
public class TelaLogin extends javax.swing.JFrame {
    
    static int id;
   

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        //utilizando bibliotecas para dimensionar o programa
        Toolkit kit = Toolkit.getDefaultToolkit();
        Dimension monitor = kit.getScreenSize();
        //capturando resolução
        int largura = monitor.width;
        int altura = monitor.height;
        //definindo tamanho da tela e centralizando a mesma
        largura*=0.35;
        altura*=0.4;
        setSize(largura,altura);
        setLocationRelativeTo( null );    
        
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnTelaLogin = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        pswSenha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblLivro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jpnTelaLogin.setBackground(new java.awt.Color(102, 102, 255));
        jpnTelaLogin.setLayout(null);

        txtUsuario.setFont(new java.awt.Font("Showcard Gothic", 2, 24)); // NOI18N
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jpnTelaLogin.add(txtUsuario);
        txtUsuario.setBounds(193, 125, 244, 36);

        pswSenha.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 24)); // NOI18N
        pswSenha.setToolTipText("");
        jpnTelaLogin.add(pswSenha);
        pswSenha.setBounds(193, 212, 244, 39);

        jButton1.setFont(new java.awt.Font("Showcard Gothic", 2, 36)); // NOI18N
        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jpnTelaLogin.add(jButton1);
        jButton1.setBounds(247, 290, 190, 64);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 2, 36)); // NOI18N
        jLabel1.setText("ExpressBook 1.0");
        jpnTelaLogin.add(jLabel1);
        jLabel1.setBounds(151, 39, 319, 45);

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 2, 36)); // NOI18N
        jLabel2.setText("Usuário: ");
        jpnTelaLogin.add(jLabel2);
        jLabel2.setBounds(10, 125, 173, 45);

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 2, 36)); // NOI18N
        jLabel3.setText("Senha: ");
        jpnTelaLogin.add(jLabel3);
        jLabel3.setBounds(52, 212, 131, 45);

        lblLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bibliotecas-para-Arduino-destaque-696x418.jpg"))); // NOI18N
        jpnTelaLogin.add(lblLivro);
        lblLivro.setBounds(-1, 2, 890, 390);

        getContentPane().add(jpnTelaLogin);
        jpnTelaLogin.setBounds(0, 0, 885, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean  c =  false;
        Comandos c1 = new Comandos();
        String usuario = txtUsuario.getText();
        String senha = pswSenha.getText();
        c = c1.Login(usuario,senha);
        if (c == true){
                c1.RetornaAtributosPessoa(usuario, senha);
                TelaRealizarEmprestimo t1 = new TelaRealizarEmprestimo();
                TelaPrincipal t2 = new TelaPrincipal();
        t2.setVisible(true);
        dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //Carregando a imagem redimensionada do livro na tela de login
            ImageIcon livro = new ImageIcon("src/Imagens/livro.png");
            livro.setImage(livro.getImage().getScaledInstance(lblLivro.getWidth(),lblLivro.getHeight(),1));
            lblLivro.setIcon(livro);
    }//GEN-LAST:event_formWindowOpened

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        // TODO add your handling code here:
        txtUsuario.setText(null);
    }//GEN-LAST:event_txtUsuarioFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
         
        
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jpnTelaLogin;
    private javax.swing.JLabel lblLivro;
    private javax.swing.JPasswordField pswSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
