/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import Bean.Livro;
import Querys.Comandos;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 *
 * @author Matheus
 */
public class TelaAlteraLivro extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaAlteraLivro
     */
    public TelaAlteraLivro() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSinopse = new javax.swing.JTextArea();
        txtNomeLivro = new javax.swing.JTextField();
        txtNomeEditora = new javax.swing.JTextField();
        txtNomeautor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnadicionarLivro = new javax.swing.JButton();
        btnDeletarLivro = new javax.swing.JButton();
        btnAlterarLivro = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbxacao = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        spiQuant = new javax.swing.JSpinner();
        cbxgenero = new javax.swing.JComboBox<>();
        txtDataLanc = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 51, 102));
        setBorder(null);
        setClosable(true);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setText("Nome do livro:");

        jLabel3.setText("Nome da editora:");

        jLabel4.setText("Nome do autor:");

        jLabel5.setText("Nome do genero:");

        jLabel6.setText("Data de lançamento:");

        jLabel7.setText("Sinopse do livro:");

        txtSinopse.setColumns(20);
        txtSinopse.setRows(5);
        jScrollPane1.setViewportView(txtSinopse);

        jLabel1.setText("Identificação do livro:");

        txtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdFocusLost(evt);
            }
        });

        btnadicionarLivro.setText("ADICIONAR LIVRO");
        btnadicionarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadicionarLivroActionPerformed(evt);
            }
        });

        btnDeletarLivro.setText("DELETAR LIVRO");
        btnDeletarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarLivroActionPerformed(evt);
            }
        });

        btnAlterarLivro.setText("ALTERAR LIVRO");
        btnAlterarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarLivroActionPerformed(evt);
            }
        });

        jLabel8.setText("Selecione a ação:");

        cbxacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a ação", "Adicionar Livro", "Alterar Livro", "Deletar Livro" }));
        cbxacao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxacaoItemStateChanged(evt);
            }
        });
        cbxacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbxacaoFocusLost(evt);
            }
        });

        jLabel9.setText("Quantidade de livros:");

        spiQuant.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        cbxgenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o gênero", "Terror", "Comédia", "Suspense" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(cbxacao, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel6)
                                .addComponent(jLabel2)
                                .addComponent(jLabel7))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnadicionarLivro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAlterarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeletarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNomeLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                                .addComponent(txtNomeEditora)
                                .addComponent(txtNomeautor))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtDataLanc, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spiQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbxgenero, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(txtNomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomeEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNomeautor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbxgenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDataLanc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(spiQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadicionarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost

    }//GEN-LAST:event_formFocusLost

    private void cbxacaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxacaoFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_cbxacaoFocusLost

    private void cbxacaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxacaoItemStateChanged

        if (cbxacao.getSelectedIndex() == 1) {
            reset();
            txtId.setEditable(false);
            btnAlterarLivro.setVisible(false);
            btnDeletarLivro.setVisible(false);
    }//GEN-LAST:event_cbxacaoItemStateChanged
        else if (cbxacao.getSelectedIndex() == 2) {
            reset();
            btnadicionarLivro.setVisible(false);
            btnDeletarLivro.setVisible(false);            
        } else if (cbxacao.getSelectedIndex() == 3) {
            reset();
            btnadicionarLivro.setVisible(false);
            btnAlterarLivro.setVisible(false);
        }

    }
    private void btnadicionarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadicionarLivroActionPerformed
        // TODO add your handling code here:
        Comandos d1 = new Comandos();
        Livro l = new Livro();
        l = preencherdados();
        d1.InserirLivro(l.getNomeLivro(),l.getNomeEditora(),l.getNomeAutor(),l.getNomeGenero(),l.getDataLancamento(),l.getSinopse(),l.getNumQuantidade(),l.getStatus());
    }//GEN-LAST:event_btnadicionarLivroActionPerformed

    private void txtIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusLost
        // TODO add your handling code here:
        
        if (cbxacao.getSelectedIndex() == 2 || cbxacao.getSelectedIndex() == 3){
        int id = Integer.parseInt(txtId.getText());
        lertabela(id);
        
        }
    }//GEN-LAST:event_txtIdFocusLost

    private void btnAlterarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarLivroActionPerformed
        // TODO add your handling code here:
        Comandos d1 = new Comandos();
        Livro l = new Livro();
        l = preencherdados();
        d1.AlterarLivro(l.getIdLivro(),l.getNomeLivro(),l.getNomeEditora(),l.getNomeAutor(),l.getNomeGenero(),l.getDataLancamento(),l.getSinopse(),l.getNumQuantidade(),l.getStatus());
        reset();
    }//GEN-LAST:event_btnAlterarLivroActionPerformed

    private void btnDeletarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarLivroActionPerformed
        // TODO add your handling code here:
        Comandos d1 = new Comandos();
        Livro l = new Livro();
        l = preencherdados();
        d1.DeletarLivro(l.getIdLivro());
        reset();
    }//GEN-LAST:event_btnDeletarLivroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarLivro;
    private javax.swing.JButton btnDeletarLivro;
    private javax.swing.JButton btnadicionarLivro;
    private javax.swing.JComboBox<String> cbxacao;
    private javax.swing.JComboBox<String> cbxgenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spiQuant;
    private javax.swing.JTextField txtDataLanc;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNomeEditora;
    private javax.swing.JTextField txtNomeLivro;
    private javax.swing.JTextField txtNomeautor;
    private javax.swing.JTextArea txtSinopse;
    // End of variables declaration//GEN-END:variables

    private void reset() {
        txtId.setEditable(true);
        txtId.setText(null);
        txtNomeLivro.setText(null);
        txtNomeEditora.setText(null);
        txtNomeautor.setText(null);
        txtSinopse.setText(null);
        cbxgenero.setSelectedIndex(0);
        spiQuant.setValue(0);
        txtDataLanc.setText(null);        
        btnAlterarLivro.setVisible(true);
        btnDeletarLivro.setVisible(true);
        btnadicionarLivro.setVisible(true);
    }
    private void lertabela(int id){
        Comandos d1 = new Comandos(); //instanciando objeto da classe comandos, que possui as querys
        for (Livro e: d1.RetornaInfoLivro(id)){ //loop de preenchimento da tabela (fornecido o index e o complemento(where) para refinamento de buscas)
            txtNomeLivro.setText(e.getNomeLivro());
            txtNomeEditora.setText(e.getNomeEditora());
            txtNomeautor.setText(e.getNomeAutor());
            cbxgenero.setSelectedItem(e.getNomeGenero());
            System.out.println(e.getDataLancamento());
            txtDataLanc.setText((e.getDataLancamento()));
            spiQuant.setValue(e.getNumQuantidade());
            txtSinopse.setText(e.getSinopse());
            }     
        }
    private Livro preencherdados(){
        Livro livro = new Livro();
        if(txtId.isEditable() == true){
        livro.setIdLivro(Integer.parseInt(txtId.getText()));
        }
        livro.setNomeLivro(txtNomeLivro.getText());
        livro.setNomeEditora(txtNomeEditora.getText());
        livro.setNomeAutor(txtNomeautor.getText());
        livro.setNomeGenero((String) cbxgenero.getSelectedItem());
        livro.setDataLancamento(txtDataLanc.getText());
        livro.setSinopse(txtSinopse.getText());
        livro.setNumQuantidade((Integer) spiQuant.getValue());
        if (livro.getNumQuantidade() > 0) {
            livro.setStatus(1);
        } else {
            livro.setStatus(0);
        }
        return livro;
    }
    
}
